apiVersion: v1
kind: Service
metadata:
  labels:
    app: lurch
  name: lurch-service
spec:
  type: NodePort
  ports:
  - name: "3000"
    nodePort: 30000
    port: 3000
    targetPort: 3000
  selector:
    app: lurch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lurch-deployment
  labels:
    app: lurch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lurch
  template:
    metadata:
      labels:
        app: lurch
    spec:
      containers:
      - image: shikaan/lurch:latest
        name: lurch
        ports:
        - containerPort: 8080
        restartPolicy: Always
        volumeMounts:
        - name: firebase-auth
          mountPath: "/home/node/firebase_auth.json"  # TODO: take me from env
          readOnly: true
          subPath: "firebase_auth.json"
        envFrom:
        - secretRef: 
            name: lurch-env
      volumes:
      - name: firebase-auth
        secret:
          secretName: firebase-auth-json
          items:
          - key: lurch_firebase_auth.json
            path: firebase_auth.json